name: Deploy Project
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Update Codesize
        uses: appleboy/ssh-action@master
        with:
          host: api.codesize.com.br
          use_insecure_cipher: true
          username: codesi80
          key: ${{ secrets.CODESIZE }}
          port: 22        
          script: |
                  cd ~/api.codesize.com.br/
                  git checkout main 
                  git pull origin main             
                  php composer.phar install --no-suggest
